# Generated by Django 4.1.2 on 2022-11-24 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SELLER',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=10)),
                ('account', models.CharField(max_length=10)),
                ('member_status', models.BooleanField(default=False)),
                ('password', models.CharField(max_length=10)),
                ('Email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=10)),
                ('ID_number', models.CharField(max_length=10)),
            ],
        ),
    ]
