# Generated by Django 4.1.2 on 2022-12-01 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wssapp', '0002_admin_cartproduct_category_customer_label_managet_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='seller',
            table='seller',
        ),
    ]
