# Generated by Django 4.1.2 on 2022-12-03 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wssapp', '0003_alter_seller_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seller',
            options={'managed': True},
        ),
    ]
