# Generated by Django 4.1.2 on 2022-11-24 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WSS', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ADMIN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=10)),
                ('username', models.CharField(max_length=10)),
                ('account', models.CharField(max_length=10)),
                ('member_status', models.BooleanField(default=False)),
                ('password', models.CharField(max_length=10)),
                ('Email', models.EmailField(max_length=254)),
            ],
        ),
    ]
