# Generated by Django 4.1.3 on 2022-11-20 04:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Maker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('country', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='PModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('maker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='welcome.maker')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(default='testProduct', max_length=15, verbose_name='雞雞名稱')),
                ('description', models.TextField(default='nothing')),
                ('year', models.PositiveIntegerField(default=2022, verbose_name='雞雞歲數')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='雞雞價格')),
                ('pmodel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='welcome.pmodel', verbose_name='雞雞型號')),
            ],
        ),
        migrations.CreateModel(
            name='PPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(default='picture', max_length=20)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='welcome.product')),
            ],
        ),
    ]
